version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 4200:4200
    working_dir: /app-frontend

  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 8080:8080
    working_dir: /app-backend
    command: dev
    volumes:
      - ./backend/src:/app-backend/src
    depends_on:
      - db
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=12345678
    # restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      # interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.36
    container_name: db
    ports:
      - 3306:3306
    environment:
      # MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 12345678
      # MYSQL_PASSWORD: yourpassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # interval: 30s
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores

