version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 80:4200
    working_dir: /app-frontend
    depends_on:
      - backend

  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 8080:8080
    working_dir: /app-backend
    volumes:
      - ./backend/src:/app-backend/src
    depends_on:
      - dbhost
    environment:
      - APP_PORT=8080
      - DB_HOST=dbhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=12345678

  dbhost:
    image: mysql:8.0.36
    container_name: dbmysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_system
      MYSQL_USER: usuariocomum
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql
