version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 4200:4200
    working_dir: /app-frontend
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 8080:8080
    working_dir: /app-backend
    depends_on:
      dbhost:
        condition: service_healthy
    volumes:
      - ./backend/src:/app-backend/src
    environment:
      - APP_PORT=8080
      - DB_HOST=dbhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=12345678
    networks:
      - app_network

  dbhost:
    container_name: dbmysql
    image: mysql:8.0.36
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_system
      MYSQL_USER: usuariocomum
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - app_network

networks:
  app_network:
    driver: bridge